GET http://localhost:8080/app/

###
POST http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
    "Body": "profane sharbert Chirpy string"
}

###
POST http://localhost:8080/api/users
Content-Type: application/json

{
    "email": "user@example.com"
}

###
POST http://localhost:8080/admin/reset

###
POST http://localhost:8080/api/chirps
Content-Type: application/json

{
    "body": "Example Chirp text with profane fornax word",
    "user_id": "8f6bef22-691a-4b21-a26c-24d890bb87b1"
}

###
GET http://localhost:8080/api/chirps

###
GET http://localhost:8080/api/chirps/a3fafc48-2dfa-4bea-a08a-f87d5307b209

###