GET http://localhost:8080/app/

###
POST http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
    "Body": "profane sharbert Chirpy string"
}

###
POST http://localhost:8080/api/users
Content-Type: application/json

{
    "email": "user@example.com",
    "password": "password"
}

###
POST http://localhost:8080/admin/reset

###
POST http://localhost:8080/api/chirps
Content-Type: application/json

{
    "body": "Example Chirp text with profane fornax word",
    "user_id": "10bf80ee-98e4-4808-babb-a5515b0ce7fe"
}

###
GET http://localhost:8080/api/chirps

###
GET http://localhost:8080/api/chirps/67a19b38-4f48-4fd6-b546-9bfb5db475bc

###
POST http://localhost:8080/api/login
Content-Type: application/json

{
    "email": "user@example.com",
    "password": "password"
}

###
POST http://localhost:8080/api/login
Content-Type: application/json

{
    "email": "user@example.com",
    "password": "password",
    "expires_in_seconds": 10
}

###