GET http://localhost:8080/app/

###
POST http://localhost:8080/admin/reset

###
POST http://localhost:8080/api/users
Content-Type: application/json

{
    "email": "user@example.com",
    "password": "password"
}

###
POST http://localhost:8080/api/login
Content-Type: application/json

{
    "email": "user@example.com",
    "password": "password"
}

###
POST http://localhost:8080/api/login
Content-Type: application/json

{
    "email": "user@example.com",
    "password": "password",
    "expires_in_seconds": 10
}

###
POST http://localhost:8080/api/chirps
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHkiLCJzdWIiOiJlMDY2MjZhYS01YjVmLTQxMmQtYjA5MC1hNjRmZjVjMjIxMmIiLCJleHAiOjE3NTIyMzEwOTEsImlhdCI6MTc1MjIzMTA4MX0.Jv0yCTQCDY-68nHnoyqO2_H76LpUzaLUW4ARQzj69CY

{
    "body": "Example Chirp text with profane fornax word"
}

###
POST http://localhost:8080/api/refresh
Authorization: Bearer 481d419581fd76e188be840393802c0b372bdfcc45df9f4213ae052feab20a1b

###

GET http://localhost:8080/api/chirps

###
GET http://localhost:8080/api/chirps/67a19b38-4f48-4fd6-b546-9bfb5db475bc

###
